
/*
 *   Copyright (c) 2013-2022. LA Referencia / Red CLARA and others
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *   This file is part of LA Referencia software platform LRHarvester v4.x
 *   For any further information please contact Lautaro Matas <lmatas@gmail.com>
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.29 at 08:39:01 AM GMT 
//


package org.lareferencia.contrib.rcaap.search.model;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.lareferencia.info/schema/4.0/search}facet-fields" minOccurs="0"/>
 *         &lt;element ref="{http://www.lareferencia.info/schema/4.0/search}facet-ranges" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="minCount" type="{http://www.w3.org/2001/XMLSchema}integer" default="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "facets")
public class Facets {

    @XmlElement(name = "facet-fields")
    protected FacetFields facetFields;
    @XmlElement(name = "facet-ranges")
    protected FacetRanges facetRanges;
    @XmlAttribute(name = "minCount")
    protected BigInteger minCount;

    /**
     * Gets the value of the facetFields property.
     * 
     * @return
     *     possible object is
     *     {@link FacetFields }
     *     
     */
    public FacetFields getFacetFields() {
        return facetFields;
    }

    /**
     * Sets the value of the facetFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacetFields }
     *     
     */
    public void setFacetFields(FacetFields value) {
        this.facetFields = value;
    }

    /**
     * Gets the value of the facetRanges property.
     * 
     * @return
     *     possible object is
     *     {@link FacetRanges }
     *     
     */
    public FacetRanges getFacetRanges() {
        return facetRanges;
    }

    /**
     * Sets the value of the facetRanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacetRanges }
     *     
     */
    public void setFacetRanges(FacetRanges value) {
        this.facetRanges = value;
    }

    /**
     * Gets the value of the minCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinCount() {
        if (minCount == null) {
            return new BigInteger("1");
        } else {
            return minCount;
        }
    }

    /**
     * Sets the value of the minCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinCount(BigInteger value) {
        this.minCount = value;
    }

}
